package com.rumahsakit.bayar.dialog;

import com.rumahsakit.bayar.dao.TarifBayarDAO;
import com.rumahsakit.bayar.model.TarifBayarModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.OperationNotSupportedException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

public class JDHargaBayar extends javax.swing.JDialog {
    
////////////////////////////////////////////////////////////////////////////////    
    
    private TarifBayarDAO tarifbayarDAO;
    private List<TarifBayarModel> m_kolomTarifBayar;
    private GenericTableModel m_tableModel;
    private TarifBayarModel m_selected;

    class GenericTableModel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return m_kolomTarifBayar.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            TarifBayarModel _eval = m_kolomTarifBayar.get(rowIndex);
            switch(columnIndex) {
                case 0:
                    return _eval.getKodebayar();
                case 1:
                    return _eval.getNama_kamar();
                case 2:
                    return _eval.getTarif();
                case 3:
                    return _eval.getKelas();
            }
            return null;
        }
        
        @Override
        public String getColumnName(int column){
            switch (column) {
                case 0:
                    return "Kode Bayar";
                case 1:
                    return "Nama Kamar";
                case 2:
                    return "Tarif";
                case 3:
                    return "Kelas";
            }
            return null;
        }
        
    }
    

public TarifBayarModel getSelectedObject() {
    return m_selected;
}

////////////////////////////////////////////////////////////////////////////////
    
    public JDHargaBayar(java.awt.Frame parent, boolean modal, List<TarifBayarModel> datas) {
        super(parent, modal);

////////////////////////////////////////////////////////////////////////////////   
        
        if(datas != null) {
            m_kolomTarifBayar = datas;
            m_tableModel = new GenericTableModel();
            
            try {
                tarifbayarDAO = TarifBayarDAO.getInstance();
            }
            
            catch (OperationNotSupportedException ex) {
                Logger.getLogger(JDHargaBayar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
///////////////////////////////////////////////////////////////////////////////////////////////////
        
        initComponents();
        
//////////////////////////////////////////////////////////////////////////////////////////////////
        
        TableTarifBayar.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                m_selected = m_kolomTarifBayar.get(TableTarifBayar.getSelectedRow());
            }
        });
        
        setTitle("Referensi Tarif Bayar");
        
///////////////////////////////////////////////////////////////////////////////////////////////////
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableTarifBayar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Referensi Tarif Harga"));

        btnClose.setText("Close");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        TableTarifBayar.setModel(m_tableModel);
        jScrollPane3.setViewportView(TableTarifBayar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        m_selected = null;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        m_selected = null;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
        TableTarifBayar.setCellSelectionEnabled(false);
    }//GEN-LAST:event_btnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
////////////////////////////////////////////////////////////////////////////////                
                
                try {
                    TarifBayarDAO _jurnalModelDAO = TarifBayarDAO.getInstance();
                    
                    List<TarifBayarModel> datas = _jurnalModelDAO.findAll();
                    JDHargaBayar dialog = new JDHargaBayar(new javax.swing.JFrame(), true, datas);
                    
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    
                        public void windowClossing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    
                    });
                    dialog.setVisible(true);
                }
                
                catch (OperationNotSupportedException ex) {
                    Logger.getLogger(JDHargaBayar.class.getName()).log(Level.SEVERE, null, ex);
                    System.err.println(ex);
                }
            }
            
////////////////////////////////////////////////////////////////////////////////            
            
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableTarifBayar;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
