/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rumahsakit.bayar.master;

import com.rumahsakit.bayar.dao.LookupDAO;
import com.rumahsakit.bayar.dao.LookupGroupDAO;
import com.rumahsakit.bayar.dao.PoliDAO;
import com.rumahsakit.bayar.dao.RumahSakitDAO;
import com.rumahsakit.bayar.dao.TarifBayarDAO;

import com.rumahsakit.bayar.utilities.koneksi;

import com.rumahsakit.bayar.model.TarifBayarModel;
import com.rumahsakit.bayar.model.Lookup;
import com.rumahsakit.bayar.model.Lookup_group;
import com.rumahsakit.bayar.model.PoliModel;
import com.rumahsakit.bayar.model.RumahSakitModel;

import com.rumahsakit.bayar.dialog.JDHargaBayar;

import java.sql.Connection;
import java.text.ParseException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class RumahSakitForm extends javax.swing.JFrame {

///////////////////////////////////////////////////////////////////////////    
    
    private Connection m_connection;
    private RumahSakitDAO m_rumahsakit;
    DefaultTableModel tabMode;
    private Lookup[] poliklinik = null;
    private Map poliklinikMap = new HashMap();
    private Lookup[] kodebayar = null;
    private Map kodebayarMap = new HashMap();
    private TarifBayarModel[] mTarifBayar = null;
    private Map TarifBayarMap = new HashMap();
    private TarifBayarDAO tarifbayardao;
    

/////////////////////////////////////////////////////////////////////////
    
    public RumahSakitForm() {
        
        LookupDAO _lookupDAO = new LookupDAO();
        poliklinik = (Lookup[]) _lookupDAO.find("KODE_POLI").toArray(new Lookup[0]);
        
        for (int i = 0; i < poliklinik.length; i++) {
            Lookup _eval = poliklinik[i];
            poliklinikMap.put(_eval.getKode_character().trim(), _eval);
        }
        
        kodebayar = (Lookup[]) _lookupDAO.find("KODE_KAMAR").toArray(new Lookup[0]);
        
        for (int i = 0; i < kodebayar.length; i++) {
            Lookup _eval = kodebayar[i];
            kodebayarMap.put(_eval.getKode_character().trim(), _eval);
        }
        
        try {
            m_connection = koneksi.bukakoneksi();
            tarifbayardao = TarifBayarDAO.getInstance();
            m_rumahsakit = new RumahSakitDAO(m_connection);
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Connection database failed with error : " +e, "form RumahSakit", JOptionPane.CLOSED_OPTION);
            e.printStackTrace();
            System.exit(0);
        }
                
        initComponents();
    }
    
    private void displayRumahSakit(RumahSakitModel value) {
        
        txt_nama.setText(value.getNama());
        
        if(value.getJkelamin().equals("L")) {
            rdn_laki.setSelected(true);
            rdn_perempuan.setSelected(false);
        }
        else {
            rdn_laki.setSelected(false);
            rdn_perempuan.setSelected(true);
        }
        
        jcmb_poliklinik.setSelectedItem(getPoliklinikByReference(value.getKodepoli()));
        
        txt_kodebayar.setText(value.getKodebayar());
        txt_tarif.setText(String.valueOf(value.getTarif()));
        txt_namakamar.setText(value.getNama_kamar());
        txt_kelas.setText(value.getKelas());
        txt_lamaperawatan.setText(String.valueOf(value.getLama()));
        txt_biayaperawatan.setText(String.valueOf(value.getBiayaperawatan()));
        
    }
    
    private Lookup getPoliklinikByReference(String value) {
        for(int i = 0; i < poliklinik.length; i++) {
            Lookup result = poliklinik[i];
            
            if(result.getKode_character().equals(value)) {
                return result;
            }
        }
        
        return null;
    }
    
    private TarifBayarModel getKeteranganTarifBayarByReference(String value) {
        for(int i = 0; i < mTarifBayar.length; i++) {
            TarifBayarModel result = mTarifBayar[i];
            if(result.getKodebayar().equals(value)) {
                return result;
            }
        }
        return null;
    }
    
    private Lookup getTarifBayarByReference(String value) {
        for (int i = 0; i < kodebayar.length; i++) {
            Lookup result = kodebayar[i];
            if (result.getKode_character().equals(value)) {
                return result;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_nopasien = new javax.swing.JTextField();
        rdn_laki = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        rdn_perempuan = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jcmb_poliklinik = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kodebayar = new javax.swing.JTextField();
        cmb_kodebayar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_namakamar = new javax.swing.JTextField();
        txt_tarif = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_kelas = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_lamaperawatan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_biayaperawatan = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txt_totalbayar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCari = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        buttonGroup1.add(rdn_laki);
        buttonGroup1.add(rdn_perempuan);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pasien"));
        jPanel1.setToolTipText("");

        jLabel3.setText("Jenis Kelamin");

        rdn_laki.setText("Laki - laki");

        jLabel1.setText("No Pasien");

        jLabel2.setText("Nama Pasien");

        rdn_perempuan.setText("Perempuan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdn_laki)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nopasien, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdn_perempuan)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nopasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdn_laki)
                    .addComponent(rdn_perempuan))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Poliklinik"));

        jcmb_poliklinik.setModel(new javax.swing.DefaultComboBoxModel(poliklinik));

        jLabel5.setText("Kode Bayar");

        jLabel4.setText("Nama Poliklinik");

        cmb_kodebayar.setText("...");
        cmb_kodebayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_kodebayarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jcmb_poliklinik, 0, 123, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_kodebayar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_kodebayar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcmb_poliklinik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_kodebayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_kodebayar))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Kamar"));

        jLabel6.setText("Tarif");

        jLabel8.setText("Kelas");

        jLabel7.setText("Nama Kamar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_namakamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(txt_tarif, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_kelas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_namakamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Perawatan"));

        jLabel9.setText("Lama Perawatan");

        jLabel10.setText("Biaya Perawatan");

        txt_biayaperawatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_biayaperawatanKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_lamaperawatan)
                    .addComponent(txt_biayaperawatan))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_lamaperawatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_biayaperawatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Bayar"));

        jLabel11.setText("Total Bayar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txt_totalbayar)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Perintah"));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addComponent(btnCari)
                .addGap(18, 18, 18)
                .addComponent(btnUbah)
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addGap(18, 18, 18)
                .addComponent(btnKeluar)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnCari)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        simpan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        
        cari();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        ubah();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        hapus();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txt_biayaperawatanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_biayaperawatanKeyReleased
        // TODO add your handling code here:
        
        perhitungan_pembayaran();
    }//GEN-LAST:event_txt_biayaperawatanKeyReleased

    private void cmb_kodebayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_kodebayarMouseClicked
        // TODO add your handling code here:
        
        JDHargaBayar _dialog = new JDHargaBayar(this, true, tarifbayardao.findAll());
        _dialog.setVisible(true);
        TarifBayarModel _data = _dialog.getSelectedObject();
        
        if (_data != null) {
            txt_kodebayar.setText(_data.getKodebayar());
            txt_tarif.setText(String.valueOf(_data.getTarif()));
            txt_namakamar.setText(_data.getNama_kamar());
            txt_kelas.setText(_data.getKelas());
            
            double _tarif = Double.parseDouble(txt_tarif.getText());
        }
    }//GEN-LAST:event_cmb_kodebayarMouseClicked

    private void perhitungan_pembayaran() {
        
        try {
            double _tarif = 0;
            int _lama_perawatan = 0;
            double _biaya_perawatan = 0;
            long total_bayar = 0; 
            
            _tarif = Double.parseDouble(txt_tarif.getText());
            _lama_perawatan = Integer.parseInt(txt_lamaperawatan.getText());
            _biaya_perawatan = Double.parseDouble(txt_biayaperawatan.getText());
            
            total_bayar = (long) ((_tarif * _lama_perawatan) + (_biaya_perawatan * _lama_perawatan));
            
            txt_totalbayar.setText(String.valueOf(total_bayar));
            
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Perhitungan Harus Numerik");
            txt_tarif.setText("0");
            txt_lamaperawatan.setText("0");
            txt_biayaperawatan.setText("0");
            txt_totalbayar.setText("0");
            
        }
        
    }
    
    private RumahSakitModel populateRumahSakit() throws ParseException {
        RumahSakitModel _result = new RumahSakitModel();
        
        _result.setNo_pasien(txt_nopasien.getText());
        _result.setNama(txt_nama.getText());
        
        if(rdn_laki.isSelected()) {
            _result.setJkelamin("L");
        }
        else if(rdn_perempuan.isSelected()) {
            _result.setJkelamin("P");
        }
        else {
            JOptionPane.showMessageDialog(null, "Jenis Kelamin Belum Dipilih");
            _result.setJkelamin("?");
        }
        
        Lookup _lookup = (Lookup) jcmb_poliklinik.getSelectedItem();
        _result.setKodepol(_lookup.getKode_character().trim());
        
        _result.setKodebayar(txt_kodebayar.getText());
        
        _result.setTarif(Double.parseDouble(txt_tarif.getText()));
        _result.setNama_kamar(txt_namakamar.getText());
        _result.setKelas(txt_kelas.getText());
        
        _result.setLama(Integer.parseInt(txt_lamaperawatan.getText()));
        _result.setBiayaperawatan(Long.parseLong(txt_biayaperawatan.getText()));
        
        _result.setTotalbayar(Double.parseDouble(txt_totalbayar.getText()));
        
        return _result;
        
    }
    
    
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RumahSakitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RumahSakitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RumahSakitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RumahSakitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RumahSakitForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmb_kodebayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox jcmb_poliklinik;
    private javax.swing.JRadioButton rdn_laki;
    private javax.swing.JRadioButton rdn_perempuan;
    private javax.swing.JTextField txt_biayaperawatan;
    private javax.swing.JTextField txt_kelas;
    private javax.swing.JTextField txt_kodebayar;
    private javax.swing.JTextField txt_lamaperawatan;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_namakamar;
    private javax.swing.JTextField txt_nopasien;
    private javax.swing.JTextField txt_tarif;
    private javax.swing.JTextField txt_totalbayar;
    // End of variables declaration//GEN-END:variables


    private String getNoPasien() {
        return txt_nopasien.getText();
    }
    
    public void cari() {
        
        String np = getNoPasien();
        
        String _no_pasien = np;
        List _result = m_rumahsakit.findRumahSakitByNoPasien(_no_pasien);
        if(!_result.isEmpty()) {
            displayRumahSakit((RumahSakitModel) _result.get(0));
            
            try {
                String _kode_bayar = getKodebayar();
                List _result2 = tarifbayardao.findKeteranganByKode(_kode_bayar);
                if(!_result2.isEmpty()) {
                    displayTarifBayar((TarifBayarModel) _result2.get(0));
                }
            }
            
            catch (Exception e) {
                
            }
        }
        
        else {
            
            JOptionPane.showMessageDialog(this, "Data Pasien not Found with No Pasien = " + _no_pasien);
            
        }
    }
    
            private void displayTarifBayar(TarifBayarModel value) {
        txt_kodebayar.setText(value.getKodebayar());
    }
    
    private String getKodebayar() {
        return txt_kodebayar.getText();
    }

    private void simpan() {
        try {
            RumahSakitModel _rumahsakit = populateRumahSakit();
            _rumahsakit = m_rumahsakit.createRumahSakit(_rumahsakit);
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            bersih();
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.CLOSED_OPTION);
            Logger.getLogger(RumahSakitForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void ubah() {
        try {
            RumahSakitModel _rumahsakit = populateRumahSakit();
            _rumahsakit = m_rumahsakit.Update(_rumahsakit);
            JOptionPane.showMessageDialog(null, "Data Terubah");
            bersih();
        }
        
        catch(Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.CLOSED_OPTION);
            Logger.getLogger(RumahSakitForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void hapus() {
        m_rumahsakit.delete(txt_nopasien.getText());
        JOptionPane.showMessageDialog(null, "Data Terhapus");
        bersih();
    }
    
    public void bersih() {
        txt_nopasien.setText(null);
        txt_nama.setText(null);
        rdn_laki.setSelected(false);
        rdn_perempuan.setSelected(false);
        txt_kodebayar.setText(null);
        txt_tarif.setText(null);
        txt_namakamar.setText(null);
        txt_kelas.setText(null);
        txt_lamaperawatan.setText(null);
        txt_biayaperawatan.setText(null);
        txt_totalbayar.setText(null);
    }
    
}
